Sports AMM - overtimemarkets
thales-markets/contracts pull request #162
Opened 2022-07-01 14:13 UTC by grujawork

2022-07-04 12:14 UTC, danijelthales requested changes

2022-07-04 13:15 UTC, grujawork commented on contracts/SportMarkets/Rundown/GamesQueue.sol
>      function dequeueGamesResolved() public onlyConsumer returns (bytes32 data) {
used in consumer

2022-07-04 13:18 UTC, grujawork commented on contracts/SportMarkets/Rundown/TherundownConsumerWrapper.sol
> +        payment = _payment;
done

2022-07-04 13:36 UTC, grujawork commented on contracts/SportMarkets/Rundown/TherundownConsumerWrapper.sol
> +        linkToken.safeTransferFrom(_sender, address(this), payment);
let's leave it because it is not a proxy

2022-07-14 09:20 UTC, danijelthales approved these changes

2022-07-14 09:20 UTC, merged