ParlayVault feature
thales-markets/contracts pull request #278
Opened 2023-02-14 19:42 UTC by hinkypunks

2023-02-21 13:56 UTC, danijelthales submitted a review, later dismissed

2023-02-21 17:18 UTC, kirilaa commented on contracts/SportMarkets/Parlay/ParlayMarketsAMM.sol
> +        uint safeBoxAmount = _getSafeBoxAmount(_sUSDPaid, sUSDAfterFees, msg.sender);
for future consistency and not braking the code:
`_getSafeBoxAmount(_sUSDPaid, sUSDAfterFees, _differentRecipient);`

with the audit merge
`_differentRecepient => _differentRecipient`

2023-02-27 23:29 UTC, danijelthales commented
Please add a new variable that will control how many times the same market can be used on tickets in the round (e.g. no more than 4 tickets in a round can contain same market)

2023-02-28 14:37 UTC, danijelthales requested changes

2023-02-28 14:37 UTC, danijelthales commented on contracts/OvertimeVaults/ParlayVault.sol
> +    uint public maxMarketNumberPerRound;
Would rename to maxMarketUsedInRoundCount

2023-02-28 14:37 UTC, danijelthales commented on contracts/OvertimeVaults/ParlayVault.sol
> +    mapping(uint => mapping(address => uint)) public marketNumberPerRound;
would rename to marketUsedInRoundCount

2023-03-03 15:33 UTC, danijelthales approved these changes

2023-03-03 15:33 UTC, merged