Add exchange to custom address (L1 <=> L2)
thales-markets/contracts pull request #88
Opened 2022-02-07 10:11 UTC by kirilantevski

- Thales to different receiver account on L2 Thales 
- Thales (L1) to different OpThales (L1) receiver account
- OpThales (L1) to different Thales (L1) receiver account

2022-02-07 13:16 UTC, kirilantevski commented
- Solution tested 
- Ready for merging

2022-02-08 09:55 UTC, danijelthales requested changes

2022-02-08 09:55 UTC, danijelthales commented on contracts/exchange_L1_L2/ThalesExchanger.sol
> +            OpThalesToken.transferFrom(_sender, address(this), _amount);
we only need this when bridging from l1 to l2, so not needed here

2022-02-08 09:55 UTC, danijelthales commented on contracts/exchange_L1_L2/ThalesExchanger.sol
> +    function exchangeThalesToOpThalesDifferentReceiver(address receiver_account, uint amount) external nonReentrant notPaused {
not needed

2022-02-08 09:55 UTC, danijelthales commented on contracts/exchange_L1_L2/ThalesExchanger.sol
> +    function exchangeOpThalesToThalesDifferentReceiver(address receiver_account, uint amount) external nonReentrant notPaused {
not needed

2022-02-08 09:55 UTC, danijelthales commented on contracts/exchange_L1_L2/ThalesExchanger.sol
> +    function exchangeThalesToL2OpThalesDifferentReceiver(address receiver_account, uint amount) external nonReentrant notPaused {
this is the only method we need

2022-02-08 14:23 UTC, danijelthales approved these changes

2022-02-08 14:23 UTC, merged